# Generated by Django 3.2.7 on 2021-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Action'), ('D', 'Drama'), ('C', 'Comedy'), ('R', 'Romance')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('language', models.CharField(choices=[('ENG', 'English'), ('GER', 'German')], max_length=3)),
                ('status', models.CharField(choices=[('RA', 'Recently Added'), ('MW', 'Most Watched'), ('TR', 'Top Rated')], max_length=2)),
                ('year_of_production', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
